[package]
name = "ksol"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["serde"] }
cxx = "=1.0.168"
cxx-qt = "0.7.3"
cxx-qt-lib = { version = "0.7.3", features = ["qt_full"] }
cxx-qt-lib-extras = "0.7.3"
env_logger = "0.11.8"
log = "0.4.27"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
sled = "0.34.7"
subprocess = "0.2.9"
which = "8.0.0"
xdg = "3.0.0"
num-traits = "0.2"
num-derive = "0.4"
tokio = { version = "1.47.1", features = ["full"] }
mpd_client = { git = "https://github.com/skorodenko/mpd_client", branch = "refactoring" }
regex = "1.11.2"
strum = { version = "0.27", features = ["derive"] }
strum_macros = "0.27"
serde_json = "1.0.143"

[build-dependencies]
cxx-qt-build = { version = "0.7.3", features = ["link_qt_object_files"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "debuginfo"
